### PR TITLE
Including .js.erb file throws error

### PR DESCRIPTION
**Pull request by joshfrench**
```
Error: module "./test" not found from "/Users/josh/src/multiple-bundles-example/app/assets/javascripts/fake_5709aa16.js"
    at notFound (/Users/josh/src/multiple-bundles-example/node_modules/browserify/index.js:812:15)
    at /Users/josh/src/multiple-bundles-example/node_modules/browserify/index.js:762:23
```

### CODE REVIEW

**Comment by cymen** [comment]
Yes, I think once you're in the browserify code, you don't want to go back "up" to sprockets again. We use `erb` to pass things from Rails to JS at the top. There might be other ways to do things but that is what works for me.

**Comment by joshfrench** [comment]
In other words the assets are bundled via Browserify first and then passed through sprockets, correct?

**Comment by cymen** [comment]
No, I believe sprockets resolves the directives like `//= require jquery` then at some point, the output after it has been resolved is piped to browserify. Then browserify is going to process the `require` directives but it knows nothing about ERB. So maybe yes? Kind of depends on how you look at it.

**Comment by joshfrench** [comment]
Thanks for the clarification!

**Pull request closed without merging**
